### ISSUE TITLE
Elaborate on the reasons why you chose aSQA

### ISSUE THREAD

**Issue by C0DK** [janschill/uni-software_architecture#13]
https://learnit.itu.dk/mod/assign/view.php?id=111893

> What do you mean here?
> 
> “They will stress the system and its architecture the most based on our quality attributes.”
> 
> You might want to add the actual scenarios (or key examples) to elaborate on this part.
> 
also

> Maybe add this as a footnote? It doesn’t exactly fit with the text.
> 
> “Weber’s Law (Contributors to Wikimedia projects).”

**Comment by janschill** [comment]
I've added some text regarding the feedback from the TAs. I really went out on a limb here to get something reasonable going.

**Comment by C0DK** [comment]
i love it.
