### ISSUE TITLE
Add one more iteration on aSQA

### ISSUE THREAD

**Issue by Trivivium** [janschill/uni-software_architecture#5]
You were supposed to do two iterations of the aSQA, one referring to the stage the system was at the time of deliverable 2 and one referring to the stage the system was at the time of deliverable 3.

(See point 1 of the deliverable guidelines).

Remember to add this part for the final report.

https://learnit.itu.dk/mod/assign/view.php?id=111893

**Comment by janschill** [comment]
This I am a bit struggling with. We were struggling with this when we did this exercise as well. It is just unclear on which two systems to do, because IMO they have not changed that much between the two deliverables.
I am going to have another and more precise look on the exact tasks in those deliverables.

**Comment by janschill** [comment]
Deliverable 2: Architectural Synthesis
>The purpose of this deliverable is to propose architectural solutions based on your architectural analysis and in particular your quality attribute scenarios.
>
>**The synthesis should be thought of as a first iteration on your architectural design, the coming deliverables will ask you to iterate on it.** The deliverable should be handed in as one (1) PDF file and build on the existing deliverables.
>
>You must:
>
>1. Describe the design decisions you have taken including the architectural style(s) and tactics chosen. Remember to argue your choices (what are the pros and cons)
>
>2. Describe the structure of your system using the 3+1 approach
>
>3. Maintain and report on an architecture backlog. The backlog should contain decisions you have to make, work you need to do, issues you have etc.

Deliverable 3: Architectural Prototyping
>The purpose of this deliverable is to create and report on an architectural prototype that aids in the design of your system. This should be thought of as part of a second iteration of architectural synthesis and as part of architectural evaluation.
>
>The deliverable should be handed in as one (1) PDF file and one (1) ZIP file containing your architectural prototype.
>
>You must:
>
>1. Argue for your architectural prototype in the sense that you identify an issue to resolve using architectural prototyping (e.g., which of two designs best solve a quality requirement), choose a type of architectural prototype (e.g., explorative or experimental), and describe how your architectural prototype is positioned with respect to the characteristics of architectural prototyping. As in the example at the lecture, you should choose a subset of your system that is both interesting and not too large.
>
>2. Zoom in into one / several components of your system and describe the corresponding detailed design with respect to the architectural prototype.  Argue your choices.
>
>3. Implement and evaluate your architectural prototype and outline implications for your system’s architecture
>
>4. Maintain and report on an architecture backlog. The backlog should contain decisions you have to make, work you need to do, issues you have etc.
>
>5. Provide your architectural prototype including source code and provide a short README.txt file in the ZIP file on how to run the prototype. Remember that the code should compile and run. In case that your prototype is cannot run in a single machine (e.g. using requiring the services of a specific software or server) please provide your code (or your configuration file) as a prof of your prototype.

**Comment by C0DK** [comment]
Asked on LearnIT
