### ISSUE TITLE
Argue about rationale for the parameters you used (prototype)

### ISSUE THREAD

**Issue by C0DK** [janschill/uni-software_architecture#7]
I am not sure what were rationale for the parameters you used. e.g 10 producers and 6 consumers.  Perhaps you can add those rationale based on your system?

**Comment by C0DK** [comment]
Perhaps discuss what are the risks of not doing architectural prototyping like you have done.

**Comment by C0DK** [comment]
AFAIK i cannot find this on page 28-29 ish. where did you write it? i assume it has to be next to the two photos in `Prototype evaluation and conclusion`

**Comment by janschill** [comment]
Sorry, I did the other parts like ”Perhaps discuss what are the risks of not doing architectural prototyping like you have done.“
Haven't done the parameters as they seem rather randomly picked. I will try to pull something out of my nose.

**Comment by janschill** [comment]
Okay I've written something for the rationale now.
